version: '3'

volumes:
  prometheus-data:
    driver: local

  grafana-data:
    driver: local

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config:/etc/prometheus
      - prometheus-data:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      metrics:

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    networks:
      metrics:

  telmon:
    build: ../
    #    ports:
    #      - '8080:8080'
    volumes:
      - ./telmon.log:/telmon.log
      - ./.telmon-config.yaml:/.telmon-config.yaml
    restart: unless-stopped
    network_mode: "host"


networks:
  metrics:

